# Default values for GetMeterDataChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#GLOBAL DATA

PORT_EXTERNAL: "80"
PORT_GRPC: "50002"
HOST_GRPC: "grpcservice"
CSV_PATH: "/data/meterusage.csv"
DATA_DOWNLOAD: ""

webserver:
  replicaCount: 3
  repository: mkud/web_grpctest
  tag: latest
  pullPolicy: Always

grpcserver:
  repository: mkud/grpc_grpctest
  tag: latest
  link_with_data: https://raw.githubusercontent.com/mkud/test_grpc/master/meter_data/meterusage.csv

ingress:
  enabled: true
  hosts:
    - host: testgrpc.local
      paths: [/]

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
