apiVersion: v1
kind: Pod
metadata:
  name: grpcserver1
  labels:
    app: grpcserver1
spec:
  containers:
  - name: grpcserver1
    image: mkud/grpc_grpctest:latest
    volumeMounts:
    - mountPath: /data
      name: datameters
    env:
    - name: PORT_GRPC
      valueFrom:
        configMapKeyRef:
          name: grpctest-config
          key: PORT_GRPC
    - name: CSV_PATH
      valueFrom:
        configMapKeyRef:
          name: grpctest-config
          key: CSV_PATH
  initContainers:
  - name: config-data
    image: busybox
    command: ["wget","$(ADDRESS_DATA)","-O","$(TO_DATA)"]
    volumeMounts:
    - name: datameters
      mountPath: /data
    env:
    - name: ADDRESS_DATA
      valueFrom:
        configMapKeyRef:
          name: grpctest-config
          key: GRPC1_ADDRESS
    - name: TO_DATA
      valueFrom:
        configMapKeyRef:
          name: grpctest-config
          key: CSV_PATH
  volumes:
  - name: datameters
    emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name: grpcservice1
spec:
  selector:
    app: grpcserver1
  clusterIP: None
  ports:
  - name: grpc
    protocol: TCP
    port: 50002
    targetPort: 50002

