apiVersion: v1
kind: Pod
metadata:
  name: grpcserver1
  labels:
    app: grpcserver1
spec:
  containers:
  - name: grpcserver1
    image: "{{ .Values.grpcserver.repository }}:{{ .Values.grpcserver.tag }}"
    volumeMounts:
    - mountPath: /data
      name: datameters
    env:
    - name: PORT_GRPC
      value: "{{ .Values.PORT_GRPC }}"
    - name: CSV_PATH
      value: "{{ .Values.CSV_PATH }}"
  initContainers:
  - name: config-data
    image: busybox
    command: ["wget","{{ .Values.grpcserver.link_with_data }}","-O","{{ .Values.CSV_PATH }}"]
    volumeMounts:
    - name: datameters
      mountPath: /data
  volumes:
  - name: datameters
    emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.HOST_GRPC }}"
spec:
  selector:
    app: grpcserver1
  clusterIP: None
  ports:
  - name: grpc
    protocol: TCP
    port: {{ .Values.PORT_GRPC }}
    targetPort: {{ .Values.PORT_GRPC }}

