---
kind: Service
apiVersion: v1
metadata:
  name: testgrpc
spec:
  selector:
    app: webserver
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.PORT_EXTERNAL }}
    targetPort: {{ .Values.PORT_EXTERNAL }}
